# Site specific settings
title: "Welcome, I'm Dahyun Chae"
name: "Portfolio"
keywords: "Key, words, about, this, website"
baseurl: ""
url: "https://ekgus419.github.io"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
#lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
github: "ekgus419"
google: "ekgus419"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
